name: flutter_application_kimpoedu_shuttlebus_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0
  get: ^4.6.5
  desktop_webview_window: ^0.2.3
  webview_windows: ^0.3.0
  # 웹 환경을 위한 패키지들
  universal_html: ^2.2.4
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7
  shelf: ^1.4.1
  shelf_static: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/ # 인증 설정 파일을 포함하도록 assets 등록
    - assets/html/
