name: flutter_application_kimpoedu_shuttlebus_manager
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0
  get: ^4.6.5
  desktop_webview_window: ^0.2.3
  webview_windows: ^0.3.0
  # 웹 환경을 위한 패키지들
  universal_html: ^2.2.4
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.7
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  window_manager: ^0.4.3
  msix: ^3.16.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/config/ # 인증 설정 파일을 포함하도록 assets 등록
    - assets/html/
    - assets/html/pinIcon/
    - assets/icon.png

msix_config:
  display_name: Route Manager
  publisher_display_name: yong
  identity_name: com.yong.routemanager
  publisher: CN=RouteManager
  msix_version: 1.0.0.0
  logo_path: assets/icon.png
  capabilities: internetClient
  store: false
  install_certificate: true
  certificate_path: D:\certificates\RouteManagerCert.pfx
  certificate_password: password123
  architecture: x64
  output_name: RouteManager
  output_path: C:\Users\smm1\OneDrive - 한밭대학교\Kmong\Navigation\ManagerProgram
  languages: ko-kr
  start_menu_icon: true
  desktop_icon: true
  build_windows: true
  sign_msix: true
